import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-categories',
  imports: [CommonModule],
  templateUrl: './categories.html',
  styleUrl: './categories.css',
})
export class Categories {
  categories = [
    {
      id: 1,
      name: 'Food & Dining',
      icon: '🍔',
      totalExpense: 18500,
      budget: 25000,
      transactions: 42,
      percentage: 74,
      monthlyChange: '+12%',
      color: 'green',
      recentExpense: 'BBQ Nation Dinner',
      status: 'On Track',
    },
    {
      id: 2,
      name: 'Travel',
      icon: '✈️',
      totalExpense: 32400,
      budget: 30000,
      transactions: 18,
      percentage: 108,
      monthlyChange: '+28%',
      color: 'blue',
      recentExpense: 'Goa Resort Booking',
      status: 'Exceeded',
    },
    {
      id: 3,
      name: 'Entertainment',
      icon: '🎬',
      totalExpense: 8400,
      budget: 12000,
      transactions: 24,
      percentage: 70,
      monthlyChange: '+8%',
      color: 'purple',
      recentExpense: 'Netflix Subscription',
      status: 'On Track',
    },
    {
      id: 4,
      name: 'Transport',
      icon: '🚕',
      totalExpense: 5200,
      budget: 10000,
      transactions: 31,
      percentage: 52,
      monthlyChange: '-4%',
      color: 'yellow',
      recentExpense: 'Uber Ride',
      status: 'Under Budget',
    },
    {
      id: 5,
      name: 'Shopping',
      icon: '🛍️',
      totalExpense: 15600,
      budget: 20000,
      transactions: 15,
      percentage: 78,
      monthlyChange: '+15%',
      color: 'pink',
      recentExpense: 'Amazon Purchase',
      status: 'On Track',
    },
    {
      id: 6,
      name: 'Utilities',
      icon: '💡',
      totalExpense: 9800,
      budget: 15000,
      transactions: 11,
      percentage: 65,
      monthlyChange: '+5%',
      color: 'cyan',
      recentExpense: 'Electricity Bill',
      status: 'On Track',
    },
  ];
}
